
development:
  adapter: postgresql
  encoding: utf8
  database: elevate_development
  pool: 5
  username: 
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: elevate_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: elevate_production
  pool: 5
  username: 
  password:
